autoInstallPeers: false
dedupePeers: true
engineStrict: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rspack/*'
  - 'rsbuild-plugin-*'

overrides:
  '@rsdoctor/agent-cli': 'https://pkg.pr.new/@rsdoctor/agent-cli@1903'
